### ISSUE TITLE
Album menu appears off side of window

### ISSUE THREAD

**Issue by eboracus** [moonwave99/playa-old#7]
I noticed that opening the "..." menu on an album has the menu appear off the side of the window, making the window wider brings it fully into view.

![electron_playa_menu](https://cloud.githubusercontent.com/assets/11758299/9019657/45c9091e-37e7-11e5-9daf-1d54c82e7225.gif)
Flickering window I guess is just an fps issue with the .gif

**Comment by moonwave99** [comment]
True - the dot menu is a leftover I am not very convinced to use, because now you can directly right-click on the row in order to access the context menu.

In case I leave the indicator there, I will position the menu consistently!

**Comment by moonwave99** [comment]
Fixed in #51
