### ISSUE TITLE
Ability to move the main window

### ISSUE THREAD

**Issue by eboracus** [moonwave99/playa-old#8]
I couldn't find a way to move the main window by clicking and dragging anywhere. Is that possible.

**Comment by moonwave99** [comment]
Hi @eboracus , as I manage my windows via [Spectacle](http://spectacleapp.com/) I barely move them around myself!

Anyways, you can actually drag the main window by clicking on the very top of it, as the resize-down cursor appear.

In the future, I plan to have a custom header with close / minimise buttons as well.
